apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: 10.110.17.138:5000/busybox:latest
      command: [ "/bin/sh", "-c", "echo -e $HDFSINFO >> /etc/hosts ; cat /etc/hosts" ]
      env:
        - name: HDFSINFO
          valueFrom:
            configMapKeyRef:
              name: hdfsinfo
              key: hdfsinfo
