# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: mr
  namespace: bigdata
  labels:
    app: mr
spec:
  ports:
  - port: 80
    name: mr
  # *.nginx.default.svc.cluster.local
  clusterIP: None
  selector:
    app: mr
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: mr
spec:
  serviceName: "mr"
  replicas: 3
  template:
    metadata:
      labels:
        app: mr
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: mr
        image: 10.110.17.138:5000/wangdk/bigdata:v0.6
        imagePullPolicy: Always
        command:
           - /usr/local/bin/start.sh
        securityContext:
          privileged: true
        env:
        - name: RESOURCEMANAGE_HOSTNAME
          value: mr-0.mr.bigdata.svc.iopk8s.com
        - name: NODE_ROLE
          value: yarn
        - name: NAMENODE_HOSTNAME
          value: master.iop.com
        - name: HDFSINFO
          valueFrom:
            configMapKeyRef:
              name: hdfsinfo
              key: hdfsinfo
        - name: SLAVES
          valueFrom:
            configMapKeyRef:
              name: hdfsinfo
              key: yarnslaves	